class GOpaque:
    def __new__(cls, argtype): ...

    class Bool:
        def __new__(self): ...

    class Int:
        def __new__(self): ...

    class Double:
        def __new__(self): ...

    class Float:
        def __new__(self): ...

    class String:
        def __new__(self): ...

    class Point:
        def __new__(self): ...

    class Point2f:
        def __new__(self): ...

    class Point3f:
        def __new__(self): ...

    class Size:
        def __new__(self): ...

    class Rect:
        def __new__(self): ...

    class Prim:
        def __new__(self): ...

    class Any:
        def __new__(self): ...


class GArray:
    def __new__(cls, argtype): ...

    class Bool:
        def __new__(self): ...

    class Int:
        def __new__(self): ...

    class Double:
        def __new__(self): ...

    class Float:
        def __new__(self): ...

    class String:
        def __new__(self): ...

    class Point:
        def __new__(self): ...

    class Point2f:
        def __new__(self): ...

    class Point3f:
        def __new__(self): ...

    class Size:
        def __new__(self): ...

    class Rect:
        def __new__(self): ...

    class Scalar:
        def __new__(self): ...

    class MatLike:
        def __new__(self): ...

    class GMat:
        def __new__(self): ...

    class Prim:
        def __new__(self): ...

    class Any:
        def __new__(self): ...


def op(op_id, in_types, out_types): ...
def kernel(op_cls): ...
