# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(612, 490)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(612, 490))
        MainWindow.setMaximumSize(QtCore.QSize(612, 490))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.splitimagefolderLabel = QtGui.QLabel(self.centralwidget)
        self.splitimagefolderLabel.setGeometry(QtCore.QRect(90, 13, 91, 16))
        self.splitimagefolderLabel.setObjectName(_fromUtf8("splitimagefolderLabel"))
        self.splitimagefolderLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.splitimagefolderLineEdit.setGeometry(QtCore.QRect(187, 11, 247, 20))
        self.splitimagefolderLineEdit.setReadOnly(True)
        self.splitimagefolderLineEdit.setObjectName(_fromUtf8("splitimagefolderLineEdit"))
        self.browseButton = QtGui.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(443, 9, 75, 24))
        self.browseButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.positionLabel = QtGui.QLabel(self.centralwidget)
        self.positionLabel.setGeometry(QtCore.QRect(37, 167, 38, 16))
        self.positionLabel.setObjectName(_fromUtf8("positionLabel"))
        self.liveimageCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.liveimageCheckBox.setEnabled(True)
        self.liveimageCheckBox.setGeometry(QtCore.QRect(170, 260, 121, 17))
        self.liveimageCheckBox.setChecked(True)
        self.liveimageCheckBox.setTristate(False)
        self.liveimageCheckBox.setObjectName(_fromUtf8("liveimageCheckBox"))
        self.positionUpButton = QtGui.QPushButton(self.centralwidget)
        self.positionUpButton.setGeometry(QtCore.QRect(44, 107, 22, 22))
        self.positionUpButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.positionUpButton.setObjectName(_fromUtf8("positionUpButton"))
        self.positionDownButton = QtGui.QPushButton(self.centralwidget)
        self.positionDownButton.setGeometry(QtCore.QRect(45, 145, 22, 22))
        self.positionDownButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.positionDownButton.setObjectName(_fromUtf8("positionDownButton"))
        self.positionLeftButton = QtGui.QPushButton(self.centralwidget)
        self.positionLeftButton.setGeometry(QtCore.QRect(25, 126, 22, 22))
        self.positionLeftButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.positionLeftButton.setObjectName(_fromUtf8("positionLeftButton"))
        self.positionRightButton = QtGui.QPushButton(self.centralwidget)
        self.positionRightButton.setGeometry(QtCore.QRect(64, 126, 22, 22))
        self.positionRightButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.positionRightButton.setObjectName(_fromUtf8("positionRightButton"))
        self.selectregionButton = QtGui.QPushButton(self.centralwidget)
        self.selectregionButton.setGeometry(QtCore.QRect(17, 72, 77, 23))
        self.selectregionButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.selectregionButton.setObjectName(_fromUtf8("selectregionButton"))
        self.similaritythresholdLabel = QtGui.QLabel(self.centralwidget)
        self.similaritythresholdLabel.setGeometry(QtCore.QRect(14, 357, 91, 16))
        self.similaritythresholdLabel.setObjectName(_fromUtf8("similaritythresholdLabel"))
        self.similaritythresholdDoubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.similaritythresholdDoubleSpinBox.setGeometry(QtCore.QRect(159, 354, 64, 22))
        self.similaritythresholdDoubleSpinBox.setMaximum(1.0)
        self.similaritythresholdDoubleSpinBox.setSingleStep(0.01)
        self.similaritythresholdDoubleSpinBox.setProperty("value", 0.9)
        self.similaritythresholdDoubleSpinBox.setObjectName(_fromUtf8("similaritythresholdDoubleSpinBox"))
        self.startautosplitterButton = QtGui.QPushButton(self.centralwidget)
        self.startautosplitterButton.setGeometry(QtCore.QRect(501, 425, 101, 31))
        self.startautosplitterButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.startautosplitterButton.setObjectName(_fromUtf8("startautosplitterButton"))
        self.resetButton = QtGui.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(501, 385, 101, 31))
        self.resetButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.undosplitButton = QtGui.QPushButton(self.centralwidget)
        self.undosplitButton.setGeometry(QtCore.QRect(410, 259, 61, 21))
        self.undosplitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.undosplitButton.setObjectName(_fromUtf8("undosplitButton"))
        self.skipsplitButton = QtGui.QPushButton(self.centralwidget)
        self.skipsplitButton.setGeometry(QtCore.QRect(490, 259, 61, 21))
        self.skipsplitButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skipsplitButton.setObjectName(_fromUtf8("skipsplitButton"))
        self.pauseLabel = QtGui.QLabel(self.centralwidget)
        self.pauseLabel.setGeometry(QtCore.QRect(14, 384, 111, 16))
        self.pauseLabel.setObjectName(_fromUtf8("pauseLabel"))
        self.pauseSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.pauseSpinBox.setGeometry(QtCore.QRect(159, 381, 64, 22))
        self.pauseSpinBox.setPrefix(_fromUtf8(""))
        self.pauseSpinBox.setDecimals(0)
        self.pauseSpinBox.setMaximum(3600.0)
        self.pauseSpinBox.setSingleStep(1.0)
        self.pauseSpinBox.setProperty("value", 10.0)
        self.pauseSpinBox.setObjectName(_fromUtf8("pauseSpinBox"))
        self.checkfpsButton = QtGui.QPushButton(self.centralwidget)
        self.checkfpsButton.setGeometry(QtCore.QRect(12, 410, 81, 21))
        self.checkfpsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkfpsButton.setObjectName(_fromUtf8("checkfpsButton"))
        self.fpsLabel = QtGui.QLabel(self.centralwidget)
        self.fpsLabel.setGeometry(QtCore.QRect(204, 410, 20, 20))
        self.fpsLabel.setObjectName(_fromUtf8("fpsLabel"))
        self.showlivesimilarityCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.showlivesimilarityCheckBox.setEnabled(True)
        self.showlivesimilarityCheckBox.setGeometry(QtCore.QRect(14, 300, 111, 17))
        self.showlivesimilarityCheckBox.setChecked(True)
        self.showlivesimilarityCheckBox.setTristate(False)
        self.showlivesimilarityCheckBox.setObjectName(_fromUtf8("showlivesimilarityCheckBox"))
        self.showhighestsimilarityCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.showhighestsimilarityCheckBox.setEnabled(True)
        self.showhighestsimilarityCheckBox.setGeometry(QtCore.QRect(14, 327, 131, 17))
        self.showhighestsimilarityCheckBox.setChecked(True)
        self.showhighestsimilarityCheckBox.setTristate(False)
        self.showhighestsimilarityCheckBox.setObjectName(_fromUtf8("showhighestsimilarityCheckBox"))
        self.livesimilarityLabel = QtGui.QLabel(self.centralwidget)
        self.livesimilarityLabel.setGeometry(QtCore.QRect(159, 303, 46, 13))
        self.livesimilarityLabel.setText(_fromUtf8(""))
        self.livesimilarityLabel.setObjectName(_fromUtf8("livesimilarityLabel"))
        self.highestsimilarityLabel = QtGui.QLabel(self.centralwidget)
        self.highestsimilarityLabel.setGeometry(QtCore.QRect(159, 330, 46, 13))
        self.highestsimilarityLabel.setText(_fromUtf8(""))
        self.highestsimilarityLabel.setObjectName(_fromUtf8("highestsimilarityLabel"))
        self.splitLabel = QtGui.QLabel(self.centralwidget)
        self.splitLabel.setGeometry(QtCore.QRect(249, 328, 61, 16))
        self.splitLabel.setObjectName(_fromUtf8("splitLabel"))
        self.resetLabel = QtGui.QLabel(self.centralwidget)
        self.resetLabel.setGeometry(QtCore.QRect(249, 365, 61, 16))
        self.resetLabel.setObjectName(_fromUtf8("resetLabel"))
        self.skiptsplitLabel = QtGui.QLabel(self.centralwidget)
        self.skiptsplitLabel.setGeometry(QtCore.QRect(249, 402, 50, 16))
        self.skiptsplitLabel.setObjectName(_fromUtf8("skiptsplitLabel"))
        self.undosplitLabel = QtGui.QLabel(self.centralwidget)
        self.undosplitLabel.setGeometry(QtCore.QRect(249, 438, 61, 16))
        self.undosplitLabel.setObjectName(_fromUtf8("undosplitLabel"))
        self.splitLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.splitLineEdit.setGeometry(QtCore.QRect(316, 326, 81, 20))
        self.splitLineEdit.setReadOnly(True)
        self.splitLineEdit.setObjectName(_fromUtf8("splitLineEdit"))
        self.undosplitLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.undosplitLineEdit.setGeometry(QtCore.QRect(316, 436, 81, 20))
        self.undosplitLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.undosplitLineEdit.setReadOnly(True)
        self.undosplitLineEdit.setObjectName(_fromUtf8("undosplitLineEdit"))
        self.skipsplitLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.skipsplitLineEdit.setGeometry(QtCore.QRect(316, 400, 81, 20))
        self.skipsplitLineEdit.setReadOnly(True)
        self.skipsplitLineEdit.setObjectName(_fromUtf8("skipsplitLineEdit"))
        self.resetLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.resetLineEdit.setGeometry(QtCore.QRect(316, 363, 81, 20))
        self.resetLineEdit.setReadOnly(True)
        self.resetLineEdit.setObjectName(_fromUtf8("resetLineEdit"))
        self.setsplithotkeyButton = QtGui.QPushButton(self.centralwidget)
        self.setsplithotkeyButton.setGeometry(QtCore.QRect(409, 326, 71, 21))
        self.setsplithotkeyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setsplithotkeyButton.setObjectName(_fromUtf8("setsplithotkeyButton"))
        self.setresethotkeyButton = QtGui.QPushButton(self.centralwidget)
        self.setresethotkeyButton.setGeometry(QtCore.QRect(410, 363, 71, 21))
        self.setresethotkeyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setresethotkeyButton.setObjectName(_fromUtf8("setresethotkeyButton"))
        self.setskipsplithotkeyButton = QtGui.QPushButton(self.centralwidget)
        self.setskipsplithotkeyButton.setGeometry(QtCore.QRect(410, 399, 71, 21))
        self.setskipsplithotkeyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setskipsplithotkeyButton.setObjectName(_fromUtf8("setskipsplithotkeyButton"))
        self.setundosplithotkeyButton = QtGui.QPushButton(self.centralwidget)
        self.setundosplithotkeyButton.setGeometry(QtCore.QRect(410, 436, 71, 21))
        self.setundosplithotkeyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setundosplithotkeyButton.setObjectName(_fromUtf8("setundosplithotkeyButton"))
        self.line_live_bottom = QtGui.QFrame(self.centralwidget)
        self.line_live_bottom.setGeometry(QtCore.QRect(111, 247, 240, 2))
        self.line_live_bottom.setFrameShadow(QtGui.QFrame.Plain)
        self.line_live_bottom.setLineWidth(1)
        self.line_live_bottom.setFrameShape(QtGui.QFrame.HLine)
        self.line_live_bottom.setObjectName(_fromUtf8("line_live_bottom"))
        self.line_live_top = QtGui.QFrame(self.centralwidget)
        self.line_live_top.setGeometry(QtCore.QRect(111, 68, 240, 2))
        self.line_live_top.setFrameShadow(QtGui.QFrame.Plain)
        self.line_live_top.setLineWidth(1)
        self.line_live_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_live_top.setObjectName(_fromUtf8("line_live_top"))
        self.line_live_right = QtGui.QFrame(self.centralwidget)
        self.line_live_right.setGeometry(QtCore.QRect(349, 69, 2, 180))
        self.line_live_right.setFrameShadow(QtGui.QFrame.Plain)
        self.line_live_right.setLineWidth(1)
        self.line_live_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_live_right.setObjectName(_fromUtf8("line_live_right"))
        self.line_left = QtGui.QFrame(self.centralwidget)
        self.line_left.setGeometry(QtCore.QRect(237, 296, 2, 163))
        self.line_left.setFrameShadow(QtGui.QFrame.Plain)
        self.line_left.setLineWidth(1)
        self.line_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_left.setObjectName(_fromUtf8("line_left"))
        self.line_live_left = QtGui.QFrame(self.centralwidget)
        self.line_live_left.setGeometry(QtCore.QRect(110, 69, 2, 180))
        self.line_live_left.setFrameShadow(QtGui.QFrame.Plain)
        self.line_live_left.setLineWidth(1)
        self.line_live_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_live_left.setObjectName(_fromUtf8("line_live_left"))
        self.line_split_left = QtGui.QFrame(self.centralwidget)
        self.line_split_left.setGeometry(QtCore.QRect(360, 69, 2, 180))
        self.line_split_left.setFrameShadow(QtGui.QFrame.Plain)
        self.line_split_left.setLineWidth(1)
        self.line_split_left.setFrameShape(QtGui.QFrame.VLine)
        self.line_split_left.setObjectName(_fromUtf8("line_split_left"))
        self.line_split_right = QtGui.QFrame(self.centralwidget)
        self.line_split_right.setGeometry(QtCore.QRect(599, 69, 2, 180))
        self.line_split_right.setFrameShadow(QtGui.QFrame.Plain)
        self.line_split_right.setLineWidth(1)
        self.line_split_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_split_right.setObjectName(_fromUtf8("line_split_right"))
        self.line_split_top = QtGui.QFrame(self.centralwidget)
        self.line_split_top.setGeometry(QtCore.QRect(361, 68, 240, 2))
        self.line_split_top.setFrameShadow(QtGui.QFrame.Plain)
        self.line_split_top.setLineWidth(1)
        self.line_split_top.setFrameShape(QtGui.QFrame.HLine)
        self.line_split_top.setObjectName(_fromUtf8("line_split_top"))
        self.line_split_bottom = QtGui.QFrame(self.centralwidget)
        self.line_split_bottom.setGeometry(QtCore.QRect(361, 247, 240, 2))
        self.line_split_bottom.setFrameShadow(QtGui.QFrame.Plain)
        self.line_split_bottom.setLineWidth(1)
        self.line_split_bottom.setFrameShape(QtGui.QFrame.HLine)
        self.line_split_bottom.setObjectName(_fromUtf8("line_split_bottom"))
        self.timerglobalhotkeysLabel = QtGui.QLabel(self.centralwidget)
        self.timerglobalhotkeysLabel.setGeometry(QtCore.QRect(313, 299, 101, 16))
        self.timerglobalhotkeysLabel.setObjectName(_fromUtf8("timerglobalhotkeysLabel"))
        self.line_right = QtGui.QFrame(self.centralwidget)
        self.line_right.setGeometry(QtCore.QRect(487, 296, 2, 163))
        self.line_right.setFrameShadow(QtGui.QFrame.Plain)
        self.line_right.setLineWidth(1)
        self.line_right.setFrameShape(QtGui.QFrame.VLine)
        self.line_right.setObjectName(_fromUtf8("line_right"))
        self.liveImage = QtGui.QLabel(self.centralwidget)
        self.liveImage.setGeometry(QtCore.QRect(111, 69, 240, 180))
        self.liveImage.setText(_fromUtf8(""))
        self.liveImage.setObjectName(_fromUtf8("liveImage"))
        self.currentSplitImage = QtGui.QLabel(self.centralwidget)
        self.currentSplitImage.setGeometry(QtCore.QRect(361, 69, 240, 180))
        self.currentSplitImage.setText(_fromUtf8(""))
        self.currentSplitImage.setObjectName(_fromUtf8("currentSplitImage"))
        self.currentsplitimageLabel = QtGui.QLabel(self.centralwidget)
        self.currentsplitimageLabel.setGeometry(QtCore.QRect(430, 50, 101, 16))
        self.currentsplitimageLabel.setObjectName(_fromUtf8("currentsplitimageLabel"))
        self.widthLabel = QtGui.QLabel(self.centralwidget)
        self.widthLabel.setGeometry(QtCore.QRect(12, 196, 31, 16))
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.heightLabel = QtGui.QLabel(self.centralwidget)
        self.heightLabel.setGeometry(QtCore.QRect(12, 227, 31, 16))
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.fpsvalueLabel = QtGui.QLabel(self.centralwidget)
        self.fpsvalueLabel.setGeometry(QtCore.QRect(160, 410, 38, 20))
        self.fpsvalueLabel.setText(_fromUtf8(""))
        self.fpsvalueLabel.setObjectName(_fromUtf8("fpsvalueLabel"))
        self.widthSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.widthSpinBox.setGeometry(QtCore.QRect(51, 193, 51, 22))
        self.widthSpinBox.setMinimum(1)
        self.widthSpinBox.setMaximum(2000)
        self.widthSpinBox.setProperty("value", 640)
        self.widthSpinBox.setObjectName(_fromUtf8("widthSpinBox"))
        self.heightSpinBox = QtGui.QSpinBox(self.centralwidget)
        self.heightSpinBox.setGeometry(QtCore.QRect(51, 224, 51, 22))
        self.heightSpinBox.setMinimum(1)
        self.heightSpinBox.setMaximum(2000)
        self.heightSpinBox.setProperty("value", 480)
        self.heightSpinBox.setObjectName(_fromUtf8("heightSpinBox"))
        self.captureregionLabel = QtGui.QLabel(self.centralwidget)
        self.captureregionLabel.setGeometry(QtCore.QRect(192, 50, 81, 16))
        self.captureregionLabel.setObjectName(_fromUtf8("captureregionLabel"))
        self.fpslimitLabel = QtGui.QLabel(self.centralwidget)
        self.fpslimitLabel.setGeometry(QtCore.QRect(14, 439, 51, 16))
        self.fpslimitLabel.setObjectName(_fromUtf8("fpslimitLabel"))
        self.fpslimitSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.fpslimitSpinBox.setGeometry(QtCore.QRect(159, 434, 64, 22))
        self.fpslimitSpinBox.setPrefix(_fromUtf8(""))
        self.fpslimitSpinBox.setDecimals(0)
        self.fpslimitSpinBox.setMinimum(30.0)
        self.fpslimitSpinBox.setMaximum(5000.0)
        self.fpslimitSpinBox.setSingleStep(1.0)
        self.fpslimitSpinBox.setProperty("value", 60.0)
        self.fpslimitSpinBox.setObjectName(_fromUtf8("fpslimitSpinBox"))
        self.splitimagefolderLabel.raise_()
        self.splitimagefolderLineEdit.raise_()
        self.browseButton.raise_()
        self.positionLabel.raise_()
        self.liveimageCheckBox.raise_()
        self.positionUpButton.raise_()
        self.positionDownButton.raise_()
        self.positionLeftButton.raise_()
        self.positionRightButton.raise_()
        self.selectregionButton.raise_()
        self.similaritythresholdLabel.raise_()
        self.similaritythresholdDoubleSpinBox.raise_()
        self.startautosplitterButton.raise_()
        self.resetButton.raise_()
        self.undosplitButton.raise_()
        self.skipsplitButton.raise_()
        self.pauseLabel.raise_()
        self.pauseSpinBox.raise_()
        self.checkfpsButton.raise_()
        self.fpsLabel.raise_()
        self.showlivesimilarityCheckBox.raise_()
        self.showhighestsimilarityCheckBox.raise_()
        self.livesimilarityLabel.raise_()
        self.highestsimilarityLabel.raise_()
        self.splitLabel.raise_()
        self.resetLabel.raise_()
        self.skiptsplitLabel.raise_()
        self.undosplitLabel.raise_()
        self.splitLineEdit.raise_()
        self.undosplitLineEdit.raise_()
        self.skipsplitLineEdit.raise_()
        self.resetLineEdit.raise_()
        self.setsplithotkeyButton.raise_()
        self.setresethotkeyButton.raise_()
        self.setskipsplithotkeyButton.raise_()
        self.setundosplithotkeyButton.raise_()
        self.line_live_bottom.raise_()
        self.line_live_top.raise_()
        self.line_live_right.raise_()
        self.line_left.raise_()
        self.line_live_left.raise_()
        self.line_split_left.raise_()
        self.line_split_right.raise_()
        self.line_split_top.raise_()
        self.line_split_bottom.raise_()
        self.timerglobalhotkeysLabel.raise_()
        self.line_right.raise_()
        self.currentsplitimageLabel.raise_()
        self.liveImage.raise_()
        self.currentSplitImage.raise_()
        self.widthLabel.raise_()
        self.heightLabel.raise_()
        self.fpsvalueLabel.raise_()
        self.widthSpinBox.raise_()
        self.heightSpinBox.raise_()
        self.captureregionLabel.raise_()
        self.fpslimitLabel.raise_()
        self.fpslimitSpinBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 612, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionView_Help = QtGui.QAction(MainWindow)
        self.actionView_Help.setObjectName(_fromUtf8("actionView_Help"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuHelp.addAction(self.actionView_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Auto Splitter", None))
        self.splitimagefolderLabel.setText(_translate("MainWindow", "Split Image Folder:", None))
        self.browseButton.setText(_translate("MainWindow", "Browse..", None))
        self.positionLabel.setText(_translate("MainWindow", "Position", None))
        self.liveimageCheckBox.setText(_translate("MainWindow", "Live Capture Region", None))
        self.positionUpButton.setText(_translate("MainWindow", "▲", None))
        self.positionDownButton.setText(_translate("MainWindow", "▼", None))
        self.positionLeftButton.setText(_translate("MainWindow", "◄", None))
        self.positionRightButton.setText(_translate("MainWindow", "►", None))
        self.selectregionButton.setText(_translate("MainWindow", "Select Region", None))
        self.similaritythresholdLabel.setText(_translate("MainWindow", "Similarity threshold", None))
        self.startautosplitterButton.setText(_translate("MainWindow", "Start Auto Splitter", None))
        self.resetButton.setText(_translate("MainWindow", "Reset", None))
        self.undosplitButton.setText(_translate("MainWindow", "Undo Split", None))
        self.skipsplitButton.setText(_translate("MainWindow", "Skip Split", None))
        self.pauseLabel.setText(_translate("MainWindow", "Pause time (seconds)", None))
        self.checkfpsButton.setText(_translate("MainWindow", "Check Max FPS", None))
        self.fpsLabel.setText(_translate("MainWindow", "FPS", None))
        self.showlivesimilarityCheckBox.setText(_translate("MainWindow", "Show live similarity", None))
        self.showhighestsimilarityCheckBox.setText(_translate("MainWindow", "Show highest similarity", None))
        self.splitLabel.setText(_translate("MainWindow", "Start / Split", None))
        self.resetLabel.setText(_translate("MainWindow", "Reset", None))
        self.skiptsplitLabel.setText(_translate("MainWindow", "Skip Split", None))
        self.undosplitLabel.setText(_translate("MainWindow", "Undo Split", None))
        self.setsplithotkeyButton.setText(_translate("MainWindow", "Set Hotkey", None))
        self.setresethotkeyButton.setText(_translate("MainWindow", "Set Hotkey", None))
        self.setskipsplithotkeyButton.setText(_translate("MainWindow", "Set Hotkey", None))
        self.setundosplithotkeyButton.setText(_translate("MainWindow", "Set Hotkey", None))
        self.timerglobalhotkeysLabel.setText(_translate("MainWindow", "Timer Global Hotkeys", None))
        self.currentsplitimageLabel.setText(_translate("MainWindow", "Current Split Image", None))
        self.widthLabel.setText(_translate("MainWindow", "Width", None))
        self.heightLabel.setText(_translate("MainWindow", "Height", None))
        self.captureregionLabel.setText(_translate("MainWindow", "Capture Region", None))
        self.fpslimitLabel.setText(_translate("MainWindow", "FPS Limit:", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionView_Help.setText(_translate("MainWindow", "View Help", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

