"""
This type stub file was generated by pyright.
"""

"""Error classes used by simplejson
"""
__all__ = ['JSONDecodeError']
def linecol(doc, pos): # -> tuple[Unknown, Unknown]:
    ...

def errmsg(msg, doc, pos, end=...): # -> str:
    ...

class JSONDecodeError(ValueError):
    """Subclass of ValueError with the following additional properties:

    msg: The unformatted error message
    doc: The JSON document being parsed
    pos: The start index of doc where parsing failed
    end: The end index of doc where parsing failed (may be None)
    lineno: The line corresponding to pos
    colno: The column corresponding to pos
    endlineno: The line corresponding to end (may be None)
    endcolno: The column corresponding to end (may be None)

    """
    def __init__(self, msg, doc, pos, end=...) -> None:
        ...
    
    def __reduce__(self): # -> tuple[Type[Self@JSONDecodeError], tuple[Unknown, Unknown, Unknown, Unknown]]:
        ...
    


