"""  # noqa: Y021
This type stub file was generated by pyright.
"""

import ctypes
import comtypes


class DXGI_SAMPLE_DESC(ctypes.Structure):
    _fields_ = ...


class D3D11_BOX(ctypes.Structure):
    _fields_ = ...


class D3D11_TEXTURE2D_DESC(ctypes.Structure):
    _fields_ = ...


class ID3D11DeviceChild(comtypes.IUnknown):
    _iid_ = ...
    _methods_ = ...


class ID3D11Resource(ID3D11DeviceChild):
    _iid_ = ...
    _methods_ = ...


class ID3D11Texture2D(ID3D11Resource):
    _iid_ = ...
    _methods_ = ...


class ID3D11DeviceContext(ID3D11DeviceChild):
    _iid_ = ...
    _methods_ = ...


class ID3D11Device(comtypes.IUnknown):
    _iid_ = ...
    _methods_ = ...


def initialize_d3d_device(dxgi_adapter) -> tuple[ctypes.pointer, ctypes.pointer]:
    ...


def describe_d3d11_texture_2d(d3d11_texture_2d) -> D3D11_TEXTURE2D_DESC:
    ...


def prepare_d3d11_texture_2d_for_cpu(d3d11_texture_2d, d3d_device) -> ctypes.pointer:
    ...
