"""  # noqa: Y021
This type stub file was generated by pyright.
"""
import enum
from typing import Any

from numpy import uint8
from numpy.typing import NDArray
from PIL import Image

#


class CaptureOutputs(enum.Enum):
    PIL = ...
    NUMPY = ...
    NUMPY_FLOAT = ...
    PYTORCH = ...
    PYTORCH_FLOAT = ...
    PYTORCH_GPU = ...
    PYTORCH_FLOAT_GPU = ...


class CaptureOutputError(BaseException):
    ...


class CaptureOutput:
    def __init__(self, backend=...) -> None:
        ...

    def process(self, pointer, pitch, size, width, height, region,
                rotation) -> Image | NDArray | NDArray[uint8] | Any:
        ...

    def to_pil(self, frame) -> Image:
        ...

    def stack(self, frames, stack_dimension) -> NDArray:
        ...
