"""  # noqa: Y021
This type stub file was generated by pyright.
"""

from typing import Any
from PIL import Image
from d3dshot.capture_outputs.numpy_capture_output import NumpyCaptureOutput


class NumpyFloatCaptureOutput(NumpyCaptureOutput):
    def process(self, pointer, pitch, size, width, height, region, rotation) -> Any:
        ...

    def to_pil(self, frame) -> Image:
        ...
