"""  # noqa: Y021
This type stub file was generated by pyright.
"""

from PIL import Image
from d3dshot.capture_outputs.pytorch_gpu_capture_output import PytorchGPUCaptureOutput


class PytorchFloatGPUCaptureOutput(PytorchGPUCaptureOutput):
    def process(self, pointer, pitch, size, width, height, region, rotation):
        ...

    def to_pil(self, frame) -> Image:
        ...
