"""  # noqa: Y021
This type stub file was generated by pyright.
https://github.com/boppreh/keyboard/issues/505
"""

canonical_names: dict[str, str]
sided_modifiers: set[str]
all_modifiers: set[str]


def normalize_name(name: str) -> str:
    ...
