""" # noqa: Y021
This type stub file was generated by pyright.
"""

from threading import Lock
from typing import NoReturn

try:
    from queue import Queue
except ImportError:
    from Queue import Queue


class GenericListener:
    lock: Lock
    handlers: list
    listening: bool
    queue: Queue

    def __init__(self) -> None:
        ...

    def invoke_handlers(self, event):
        ...

    def start_if_necessary(self) -> None:
        ...

    def pre_process_event(self, event):
        ...

    def process(self) -> NoReturn:
        ...

    def add_handler(self, handler) -> None:
        ...

    def remove_handler(self, handler) -> None:
        ...
