""" # noqa: Y021
This type stub file was generated by pyright.
https://github.com/boppreh/keyboard/issues/505
"""
from typing import Any, Literal

Unknown = Any


KEY_DOWN: Literal["down"]
KEY_UP: Literal["up"]


class KeyboardEvent:
    event_type: None | Literal['down', 'up'] = ...
    scan_code: None | int = ...
    name: None | str = ...
    time: None | float = ...
    device: Unknown | None = ...
    modifiers: None | tuple = ...
    is_keypad: None | bool = ...

    def __init__(
            self,
            event_type: None | Literal['down', 'up'],
            scan_code: None | int,
            name: None | str = ...,
            time: None | float = ...,
            device: Unknown | None = ...,
            modifiers: None | tuple = ...,
            is_keypad: None | bool = ...) -> None:
        ...

    def to_json(self, ensure_ascii: bool = ...) -> str:
        ...

    def __eq__(self, other: KeyboardEvent) -> bool:
        ...
