""" # noqa: Y021
This type stub file was generated by pyright.
"""
from __future__ import annotations

from typing import Literal, Optional

KEY_DOWN: Literal["down"]
KEY_UP: Literal["up"]


class KeyboardEvent:
    event_type: Optional[Literal['down', 'up']] = ...
    scan_code: Optional[int] = ...
    name: Optional[str] = ...
    time: Optional[float] = ...
    device: Optional = ...
    modifiers: Optional[tuple] = ...
    is_keypad: Optional[bool] = ...

    def __init__(
            self,
            event_type: Optional[Literal['down', 'up']],
            scan_code: Optional[int],
            name: Optional[str] = ...,
            time: Optional[float] = ...,
            device: Optional = ...,
            modifiers: Optional[tuple] = ...,
            is_keypad: Optional[bool] = ...) -> None:
        ...

    def to_json(self, ensure_ascii: bool = ...) -> str:
        ...

    def __eq__(self, other: KeyboardEvent) -> bool:
        ...
