# Form implementation generated from reading ui file './res/about.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_aboutAutoSplitWidget(object):
    def setupUi(self, aboutAutoSplitWidget):
        aboutAutoSplitWidget.setObjectName("aboutAutoSplitWidget")
        aboutAutoSplitWidget.resize(264, 250)
        aboutAutoSplitWidget.setMinimumSize(QtCore.QSize(264, 250))
        aboutAutoSplitWidget.setMaximumSize(QtCore.QSize(264, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        aboutAutoSplitWidget.setWindowIcon(icon)
        self.okButton = QtWidgets.QPushButton(aboutAutoSplitWidget)
        self.okButton.setGeometry(QtCore.QRect(180, 220, 75, 24))
        self.okButton.setObjectName("okButton")
        self.createdbyLabel = QtWidgets.QLabel(aboutAutoSplitWidget)
        self.createdbyLabel.setGeometry(QtCore.QRect(10, 44, 161, 32))
        self.createdbyLabel.setObjectName("createdbyLabel")
        self.versionLabel = QtWidgets.QLabel(aboutAutoSplitWidget)
        self.versionLabel.setGeometry(QtCore.QRect(10, 21, 161, 16))
        self.versionLabel.setObjectName("versionLabel")
        self.donatetextLabel = QtWidgets.QLabel(aboutAutoSplitWidget)
        self.donatetextLabel.setGeometry(QtCore.QRect(30, 95, 204, 32))
        self.donatetextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.donatetextLabel.setObjectName("donatetextLabel")
        self.donatebuttonLabel = QtWidgets.QLabel(aboutAutoSplitWidget)
        self.donatebuttonLabel.setGeometry(QtCore.QRect(60, 150, 147, 47))
        self.donatebuttonLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.donatebuttonLabel.setObjectName("donatebuttonLabel")
        self.iconLabel = QtWidgets.QLabel(aboutAutoSplitWidget)
        self.iconLabel.setGeometry(QtCore.QRect(190, 17, 62, 71))
        self.iconLabel.setObjectName("iconLabel")

        self.retranslateUi(aboutAutoSplitWidget)
        self.okButton.clicked.connect(aboutAutoSplitWidget.close)
        QtCore.QMetaObject.connectSlotsByName(aboutAutoSplitWidget)

    def retranslateUi(self, aboutAutoSplitWidget):
        _translate = QtCore.QCoreApplication.translate
        aboutAutoSplitWidget.setWindowTitle(_translate("aboutAutoSplitWidget", "About AutoSplit"))
        self.okButton.setText(_translate("aboutAutoSplitWidget", "OK"))
        self.createdbyLabel.setText(_translate("aboutAutoSplitWidget", "<html><head/><body><p>Created by <a href=\"https://twitter.com/toufool\"><span style=\" text-decoration: underline; color:#0000ff;\">Toufool</span></a> and <a href=\"https://twitter.com/faschz\"><span style=\" text-decoration: underline; color:#0000ff;\">Faschz</span></a><br/>Maintained by <a href=\"https://twitter.com/Avasam06\"><span style=\" text-decoration: underline; color:#0000ff;\">Avasam</span></a></p></body></html>"))
        self.versionLabel.setText(_translate("aboutAutoSplitWidget", "Version: "))
        self.donatetextLabel.setText(_translate("aboutAutoSplitWidget", "If you enjoy using this program, please\n"
"consider donating. Thank you!"))
        self.donatebuttonLabel.setText(_translate("aboutAutoSplitWidget", "<html><head/><body><p><a href=\"https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=BYRHQG69YRHBA&amp;item_name=AutoSplit+development&amp;currency_code=USD&amp;source=url\"><img src=\":/resources/btn_donateCC_LG.png\"/></a></p></body></html>"))
        self.iconLabel.setText(_translate("aboutAutoSplitWidget", "<html><head/><body><p><img src=\":/resources/icon.ico\"/></p></body></html>"))
