# Form implementation generated from reading ui file '.\res\update_checker.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UpdateChecker(object):
    def setupUi(self, UpdateChecker):
        UpdateChecker.setObjectName("UpdateChecker")
        UpdateChecker.setEnabled(True)
        UpdateChecker.resize(313, 133)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UpdateChecker.sizePolicy().hasHeightForWidth())
        UpdateChecker.setSizePolicy(sizePolicy)
        UpdateChecker.setMinimumSize(QtCore.QSize(313, 133))
        UpdateChecker.setMaximumSize(QtCore.QSize(313, 133))
        UpdateChecker.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.labelUpdateStatus = QtWidgets.QLabel(UpdateChecker)
        self.labelUpdateStatus.setGeometry(QtCore.QRect(17, 10, 281, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUpdateStatus.sizePolicy().hasHeightForWidth())
        self.labelUpdateStatus.setSizePolicy(sizePolicy)
        self.labelUpdateStatus.setText("")
        self.labelUpdateStatus.setObjectName("labelUpdateStatus")
        self.labelCurrentVersion = QtWidgets.QLabel(UpdateChecker)
        self.labelCurrentVersion.setGeometry(QtCore.QRect(17, 30, 91, 16))
        self.labelCurrentVersion.setObjectName("labelCurrentVersion")
        self.labelLatestVersion = QtWidgets.QLabel(UpdateChecker)
        self.labelLatestVersion.setGeometry(QtCore.QRect(17, 50, 81, 16))
        self.labelLatestVersion.setObjectName("labelLatestVersion")
        self.labelGoToDownload = QtWidgets.QLabel(UpdateChecker)
        self.labelGoToDownload.setGeometry(QtCore.QRect(17, 103, 241, 16))
        self.labelGoToDownload.setText("")
        self.labelGoToDownload.setObjectName("labelGoToDownload")
        self.pushButtonLeft = QtWidgets.QPushButton(UpdateChecker)
        self.pushButtonLeft.setGeometry(QtCore.QRect(150, 100, 75, 24))
        self.pushButtonLeft.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButtonLeft.setText("")
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.pushButtonRight = QtWidgets.QPushButton(UpdateChecker)
        self.pushButtonRight.setGeometry(QtCore.QRect(230, 100, 75, 24))
        self.pushButtonRight.setText("")
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.labelCurrentVersionNumber = QtWidgets.QLabel(UpdateChecker)
        self.labelCurrentVersionNumber.setGeometry(QtCore.QRect(120, 32, 181, 16))
        self.labelCurrentVersionNumber.setText("")
        self.labelCurrentVersionNumber.setObjectName("labelCurrentVersionNumber")
        self.labelLatestVersionNumber = QtWidgets.QLabel(UpdateChecker)
        self.labelLatestVersionNumber.setGeometry(QtCore.QRect(120, 50, 181, 16))
        self.labelLatestVersionNumber.setText("")
        self.labelLatestVersionNumber.setObjectName("labelLatestVersionNumber")

        self.retranslateUi(UpdateChecker)
        self.pushButtonRight.clicked.connect(UpdateChecker.close)
        QtCore.QMetaObject.connectSlotsByName(UpdateChecker)

    def retranslateUi(self, UpdateChecker):
        _translate = QtCore.QCoreApplication.translate
        UpdateChecker.setWindowTitle(_translate("UpdateChecker", "Update Checker"))
        self.labelCurrentVersion.setText(_translate("UpdateChecker", "Current Version:"))
        self.labelLatestVersion.setText(_translate("UpdateChecker", "Latest Version:"))
